#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

# if i just did DEV_ENV=$(pwd) ./run then this is needed for the rest of the
# scripts
export DEV_ENV="$DEV_ENV"

filter=""
dry="0"

# while argument count is > 0
while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    # shift: remove first argument of the arg list
    shift
done

log() {
   if [[ $dry == "1" ]]; then
       # @: all
       echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
   log "execute $@"
   if [[ $dry == "1" ]]; then
       return
   fi
   # execute everything
   "$@" 
}


log "$script_dir -- $filter"

cd $script_dir
# maxdepth 1: not recursively deep
# mindepth 1: no dot files
# type f: type file
scripts=$(find ./runs -maxdepth 1 -mindepth 1 -executable -type f)

for script in $scripts; do
    # -qv: quiet and inverse match
    if echo "$script" | grep -qv "$filter"; then
        log "filtering $script"
        continue
    fi

    execute ./$script
done
