#!/usr/bin/env bash
# Shellchecker
#
# Checks the shell scripts; hardcoded
#
# Usage:
#	bash shellchecker

set -euo pipefail

install_scripts=(
	"shellchecker"
	"dev-env"
	"run"
	"lib/common.sh"
	"lib/optimize.sh"
	"lib/optimize-no-lto.sh"
	"packages.d/01-dev"
	"packages.d/02-cpp-toolchain"
	"packages.d/03-lua-toolchain"
	"packages.d/04-vim"
	"packages.d/05-rust-toolchain"
	"packages.d/06-cuda"
	"packages.d/07-perf"
	"packages.d/08-tree-sitter"
    "packages.d/intel-tools"
	"packages.d/neovim"
	"packages.d/xx-Clean"
    "packages.d/xx-HyDE"
)

for script in "${install_scripts[@]}"; do
	echo "Checking $script..."
    if ! shellcheck -x -P lib -P . -S style "$script"; then
		echo
        echo "ERROR: shellcheck failed for $script" >&2
        exit 1
	fi
done

