#!/usr/bin/env bash

git clone -b v0.11.2 https://github.com/neovim/neovim.git $HOME/personal/neovim
sudo pacman -Sy cmake gettext lua 

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
