#!/usr/bin/env bash
# packages.d/rust-toolchain
#
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
# shellcheck source=../lib/common.sh
source "$script_dir/lib/common.sh"

log_info "---- rust-toolchain ----"

run_cmd mkdir -p "$HOME/personal/rusty"
(
    cd -- "$HOME/personal/rusty"
    run_cmd mkdir -p "$HOME/.cargo/tmp"

    export TMPDIR="$HOME/.cargo/tmp" 
	run_cmd curl --proto '=https' --tlsv1.2 -sSf \
		https://sh.rustup.rs | sh -s -- -y --profile default --default-toolchain stable
)
run_cmd rm -Rf -- "$HOME/.cargo/tmp/"
run_cmd eval ". \"$HOME/.cargo/env\""
