#!/usr/bin/env bash
# packages.d/cuda -- CUDA toolkit + cuDNN
# TODO: install from source ?
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
# shellcheck source=../lib/common.sh
source "$script_dir/lib/common.sh"
# shellcheck source=../lib/optimize.sh
source "$script_dir/lib/optimize.sh"

log_info "---- treesitter ----"
require_cmd cargo

run_cmd  cargo install --locked tree-sitter-cli

