#!/usr/bin/env bash
# packages.d/tree-sitter
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
# shellcheck source=../lib/common.sh
source "$script_dir/lib/common.sh"
# shellcheck source=../lib/optimize-no-lto.sh
source "$script_dir/lib/optimize-no-lto.sh"

log_info "---- treesitter ----"
require_cmd cargo

personal_dir="$HOME/personal"
tree_sitter_src="$personal_dir/tree-sitter"
release_v="release-0.26"
 
mkdir -p -- "$personal_dir"

if [[ -d "$tree_sitter_src/.git" ]]; then
	log_info "tree-sitter already cloned at $tree_sitter_src, pulling latest instead"
 	run_cmd git -C "$tree_sitter_src" pull --ff-only
else
     run_cmd git clone --depth 1 -b "$release_v" https://github.com/tree-sitter/tree-sitter.git "$tree_sitter_src"
fi

(
	cd -- "$tree_sitter_src"/crates/cli
    
    TMPDIR=$HOME/.cargo/tmp cargo build --profile optimize -p tree-sitter-cli
    cp "$tree_sitter_src/target/optimize/tree-sitter" "$HOME/.cargo/bin/"
)
run_cmd rm -rf "$HOME/.cargo/tmp/"
