#!/usr/bin/env bash
# packages.d/intel-tools
# TODO: install from source?
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
# shellcheck source=../lib/common.sh
source "$script_dir/lib/common.sh"
# shellcheck source=../lib/optimize.sh
source "$script_dir/lib/optimize.sh"

log_info "---- intel-tools ----"

run_cmd sudo pacman -S --noconfirm --needed intel-oneapi-toolkit
run_cmd . /opt/intel/oneapi/setvars.sh
log_info "New shell should source /opt/intel/oneapi/setvars.sh"
