#!/usr/bin/env bash

git clone -b stable https://github.com/neovim/neovim.git $HOME/personal/neovim
cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=Release
sudo make install

git clone https://github.com/nvim-lua/plenary.nvim.git $HOME/personal/plenary.nvim

